version: '3.4'

services:
  traning.microservices.basket:
    image: ${DOCKER_REGISTRY-}traning.microservices.basket
    build:
      context: .
      dockerfile: Traning.AspNetCore.Microservices.Basket.API/Dockerfile
  traning.microservices.catalog:
    image: ${DOCKER_REGISTRY-}traning.microservices.catalog
    build:
      context: .
      dockerfile: Traning.AspNetCore.Microservices.Catalog.API/Dockerfile
  traning.microservices.jaeger:
    image: jaegertracing/all-in-one:latest
  traning.microservices.database:
    image: "mcr.microsoft.com/mssql/server"
